### ISSUE TITLE
Failed to detect use-after-free when malloc more than 2MB buffer

### ISSUE THREAD

**Issue by Marsman1996** [purdue-secomp-lab/MEDS#3]
MEDS fails to detect UAF error of the following malloc-free-malloc-use code with 2MB or larger buffer size:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(){
    char *a = malloc(0x200000); // 2MB
    // char *a = malloc(0x10000); // 64KB
    printf("a = %p\n", a);
    free(a);
    
    char *b;
    for(int i = 0; ; i++){
        b = malloc(0x200000);
        printf("i = %d, a = %p, b = %p\n", i, a, b);
        if(a == b)
            break;
        free(b);
    }
    
    int offset = 0x10;
    printf("writing in %p\n", (a+offset));
    a[offset] = 'a';

    free(b);
    return 0;
}
```

I compile and run this code in the docker with MEDS

```
$ docker run -v ~/MEDS/sample:/data --cap-add=SYS_PTRACE -it --rm meds /bin/bash
$ clang -fsanitize=meds -g -mllvm -meds-stack=1 -mllvm -meds-global=1 -mcmodel=large -Wl,--emit-relocs uaf-3.c -o uaf-3-meds
$ ./uaf-3-meds
```

Theoretically it should not break the for loop since the quarantine zone is 80T. 
But the address of 'b' is equal to the address of 'a' during the first malloc.

But if the buffer is small (like 64KB), the 80T quarantine zone mechanism works fine.

**Comment by whhan** [comment]
Good point! Thank you for doing some tests with MEDS. ASan and MEDS have two heap allocators: i) primary allocator for small chunks, and ii) secondary allocator for large chunks. I didn't focus on the secondary, while ASan maintains fixed size quarantine zone to quarantine chunks of both allocators. To release physical pages while maintaining virtual pages, mapping with no permission right after the unmapping within single transaction (atomitically) should work. 80TB in the paper is for primary allocator. This change may lead to insufficient pages and fails to mmap, since MEDS does not handle when virtual pages are exhausted. Thus, we may reduce the size of primary allocator. The patch has been merged. Please leave some comments here if something is wrong when you conduct further testings. I will leave this issue opened until you verify the change.

**Comment by whhan** [comment]
The patch has been merged. Please leave some comments here if something is wrong when you conduct further testings. I will leave this issue opened until you verify the change.

**Comment by Marsman1996** [comment]
I'm glad to be helpful.
After the patch the 80T quarantine zone mechanism now works fine.
I have another question about the redzone and i will open a new issue to talk about it.
